<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{d7bd07a9-632a-4512-a44e-2ca193c0ff70}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	AxisControl : AxisControl;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AxisControl();
//AxisControl2();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>